blank_issues_enabled: false
contact_links:
  - name: â“ Pregunta / Duda general
    url: https://github.com/grcodedigitalsolutions/GR_Leviatan/discussions
    about: "Para preguntas que no son bugs ni features."
